### ISSUE TITLE
x86 calling conventions diagrams

### ISSUE THREAD

**Issue by normster** [cs161-staff/textbook#102]
Is red supposed to show everything that's new in each step of the diagrams? If so, there are some very minor inconsistencies which threw me off slightly while reviewing.

* Step 2: should the arrow from `rip` to `main` should be red?
* Step 3: should the arrow pointing from the empty row to the top of the stack frame first appear in step 4?
* Step 4: should the arrow pointing from the empty row to the top of the stack frame be red?

**Comment by ashmchiu** [comment]
I agree to the Step 2/3 changes (can implement them later).
Could I get more clarity on Step 4? Do you mean the arrow that shows that the old ebp (sfp) points to the top of the stack frame for main?

**Comment by normster** [comment]
I just mean that since that arrow first appears in step 4, maybe it should be red?

**Comment by normster** [comment]
Oh yeah the PR is exactly what I meant
