### ISSUE TITLE
LaTeX mistake in MAC page

### ISSUE THREAD

**Issue by ryancottone** [cs161-staff/textbook#38]
https://edstem.org/us/courses/32975/discussion/2584575?comment=5951651

![image](https://user-images.githubusercontent.com/34407608/219268291-cf2a6f4c-5aba-4cac-b33b-49eba553206c.png)

Formula should read $$S_i = AES_{K_1}(S_{i-1} \oplus P_i)$$

**Comment by peyrin** [comment]
Closed via https://github.com/cs161-staff/textbook/pull/45
