### ISSUE TITLE
Typos (from student email)

### ISSUE THREAD

**Issue by peyrin** [cs161-staff/textbook#41]
A student sent these to [cs161-staff@berkeley.edu](mailto:cs161-staff@berkeley.edu). I have not checked the correctness/validity of these edits, but putting them here for later.

Both in chapter 6.

Typo 1: "Eve might also be allowed to trick Alice into decrypting some ciphertexts of Eve's choosing." This should say Bob instead of Alice.

Typo 2: OFB mode encryption formula in Section 6 appears to have incorrect LaTeX.

**Comment by ronyw7** [comment]
Hi, I'm a current student in 161 and also noticed the typo in OFB mode formula. Here's a screenshot for quick reference.

<img width="802" alt="Screenshot 2023-07-10 at 02 31 29" src="https://github.com/cs161-staff/textbook/assets/78146401/47712fbe-e4e7-41d6-a4b8-70b1efe7c5d8">
