### ISSUE TITLE
Memory Safety Vulnerabilities Diagram Says "FSP" instead of "SFP"

### ISSUE THREAD

**Issue by Lawrence1024** [cs161-staff/textbook#50]
Under Chapter 3 at https://textbook.cs161.org/memory-safety/vulnerabilities.html

**Comment by rqchao** [comment]
If you're referring to 3.5, FSP is meant to denote the original SFP is overwritten.

**Comment by peyrin** [comment]
The diagram in section 3.5 is correct as-is. Starting in Step 2, the SFP is overwritten, and the paper we linked refers to this overwritten value as the "forged saved frame pointer", or FSP.
