### ISSUE TITLE
[Small Typo] Display Issue with `W\^X` on Mitigations Page

### ISSUE THREAD

**Issue by pufanyi** [cs161-staff/textbook#74]
Hello,

Thanks so much for the great textbook!

I noticed a small display issue on the mitigations page of the CS161 textbook. The text `W\^X` does not render correctly in the browser; it appears to be a typo or formatting error.

https://github.com/cs161-staff/textbook/blob/1e30910875229d77212d85b43f470998f0334ea3/memory-safety/mitigations.md?plain=1#L41

Here is how it looks in my browser ([link here](https://textbook.cs161.org/memory-safety/mitigations.html#45-mitigation-non-executable-pages)):

![1719013278100](https://github.com/cs161-staff/textbook/assets/44887683/c7c75885-f87f-4106-b2ac-d92ed56db5db)

It might be more appropriate to change it to `W^X` for the correct display.

Thank you!

**Comment by ashmchiu** [comment]
closed by #75

**Comment by ashmchiu** [comment]
closed by #75
